import { Book } from "./types/book";

const data: Book[] = [
  {
    bookId: 1,
    title: "Pride and Prejudice",
    publisher: "Jane",
    author: "Austen",
    type: "Hardcover",
    isbn: "1234567891",
    category: "Fiction",
    availableCopies: "20/100",
  },
  {
    bookId: 2,
    title: "To Kill a Mockingbird",
    publisher: "Harper",
    author: "Lee",
    type: "Paperback",
    isbn: "1234567892",
    category: "Fiction",
    availableCopies: "10/75",
  },
  {
    bookId: 3,
    title: "The Catcher in the Rye",
    publisher: "J.D.",
    author: "Salinger",
    type: "Hardcover",
    isbn: "1234567893",
    category: "Fiction",
    availableCopies: "5/50",
  },
  {
    bookId: 4,
    title: "The Great Gatsby",
    publisher: "F. Scott",
    author: "Fitzgerald",
    type: "Hardcover",
    isbn: "1234567894",
    category: "Non-Fiction",
    availableCopies: "28/50",
  },
  {
    bookId: 5,
    title: "The Alchemist",
    publisher: "Paulo",
    author: "Coelho",
    type: "Hardcover",
    isbn: "1234567895",
    category: "Biography",
    availableCopies: "15/50",
  },
  {
    bookId: 6,
    title: "The Book Thief",
    publisher: "Markus",
    author: "Zusak",
    type: "Hardcover",
    isbn: "1234567896",
    category: "Mystery",
    availableCopies: "64/75",
  },
  {
    bookId: 7,
    title: "The Chronicles of Narnia",
    publisher: "C.S.",
    author: "Lewis",
    type: "Paperback",
    isbn: "1234567897",
    category: "Sci-Fi",
    availableCopies: "86/100",
  },
  {
    bookId: 8,
    title: "The Da Vinci Code",
    publisher: "Dan",
    author: "Brown",
    type: "Paperback",
    isbn: "1234567898",
    category: "Sci-Fi",
    availableCopies: "10/50",
  },
  {
    bookId: 9,
    title: "The Grapes of Wrath",
    publisher: "John",
    author: "Steinbeck",
    type: "Hardcover",
    isbn: "1234567899",
    category: "Fiction",
    availableCopies: "15/50",
  },
  {
    bookId: 10,
    title: "The Hitchhiker's Guide to the Galaxy",
    publisher: "Douglas",
    author: "Adams",
    type: "Paperback",
    isbn: "1234567900",
    category: "Non-Fiction",
    availableCopies: "15/50",
  },
  {
    bookId: 11,
    title: "Moby-Dick",
    publisher: "Herman",
    author: "Melville",
    type: "Hardcover",
    isbn: "8901234567",
    category: "Fiction",
    availableCopies: "22/30",
  },
  {
    bookId: 12,
    title: "To Kill a Mockingbird",
    publisher: "Harper",
    author: "Lee",
    type: "Paperback",
    isbn: "9012345678",
    category: "Non-Fiction",
    availableCopies: "20/20",
  },
  {
    bookId: 13,
    title: "The Catcher in the Rye",
    publisher: "J.D.",
    author: "Salinger",
    type: "Hardcover",
    isbn: "0123456789",
    category: "Non-Fiction",
    availableCopies: "9/10",
  },
];

export default data;
